import type { ExamplePreset } from '@/types';

export const EXAMPLE_PRESETS: ExamplePreset[] = [
  {
    id: 'beginner',
    name: '초보 셀러 예시',
    description: '스마트스토어에서 1만원 상품 판매',
    values: {
      sellingPrice: 10000,
      productCost: 4000,
      discountRate: 0,
      discountAmount: 0,
      platformFeeRate: 5.5,
      paymentFeeRate: 3.74,
      couponBurden: 0,
      sellerShippingCost: 2500,
      customerShippingCost: 0,
      packagingCost: 300,
      materialCost: 100,
      advertisingCost: 0,
      otherCosts: 0,
      sellingPriceVatIncluded: true,
      wholesaleVatType: 'excluded',
      targetMarginRate: 30,
    },
  },
  {
    id: 'clothing',
    name: '의류 셀러 예시',
    description: '에이블리에서 3만원 의류 판매',
    values: {
      sellingPrice: 30000,
      productCost: 10000,
      discountRate: 0,
      discountAmount: 0,
      platformFeeRate: 15,
      paymentFeeRate: 0,
      couponBurden: 0,
      sellerShippingCost: 3000,
      customerShippingCost: 0,
      packagingCost: 500,
      materialCost: 200,
      advertisingCost: 500,
      otherCosts: 0,
      sellingPriceVatIncluded: true,
      wholesaleVatType: 'excluded',
      targetMarginRate: 35,
    },
  },
  {
    id: 'beauty',
    name: '뷰티 셀러 예시',
    description: '자사몰에서 2만5천원 화장품 판매',
    values: {
      sellingPrice: 25000,
      productCost: 8000,
      discountRate: 0,
      discountAmount: 0,
      platformFeeRate: 0,
      paymentFeeRate: 3.3,
      couponBurden: 0,
      sellerShippingCost: 0,
      customerShippingCost: 3000,
      packagingCost: 800,
      materialCost: 300,
      advertisingCost: 1000,
      otherCosts: 0,
      sellingPriceVatIncluded: true,
      wholesaleVatType: 'included',
      targetMarginRate: 40,
    },
  },
  {
    id: 'free_shipping',
    name: '무료배송 예시',
    description: '쿠팡에서 5만원 상품 무료배송 판매',
    values: {
      sellingPrice: 50000,
      productCost: 20000,
      discountRate: 0,
      discountAmount: 0,
      platformFeeRate: 10.8,
      paymentFeeRate: 0,
      couponBurden: 0,
      sellerShippingCost: 3500,
      customerShippingCost: 0,
      packagingCost: 500,
      materialCost: 200,
      advertisingCost: 1500,
      otherCosts: 0,
      sellingPriceVatIncluded: true,
      wholesaleVatType: 'excluded',
      targetMarginRate: 25,
    },
  },
];
