import type { ExamplePreset } from '@/types';

export const EXAMPLE_PRESETS: ExamplePreset[] = [
  {
    id: 'beginner',
    name: '초보 셀러 예시',
    description: '스마트스토어에서 1만원 상품 판매 (3억 이하 등급)',
    values: {
      sellingPrice: 10000,
      productCost: 4000,
      discountRate: 0,
      discountAmount: 0,
      platformFeeRate: 2.73,
      paymentFeeRate: 1.98,
      couponBurden: 0,
      sellerShippingCost: 2500,
      customerShippingCost: 0,
      packagingCost: 300,
      materialCost: 100,
      advertisingCost: 0,
      otherCosts: 0,
      sellingPriceVatIncluded: true,
      wholesaleVatType: 'included',
      targetMarginRate: 30,
    },
  },
  {
    id: 'coupang_mp',
    name: '쿠팡 자체배송',
    description: '쿠팡 마켓플레이스 생활용품 3만원',
    values: {
      sellingPrice: 30000,
      productCost: 12000,
      discountRate: 0,
      discountAmount: 0,
      platformFeeRate: 7.8,
      paymentFeeRate: 0,
      couponBurden: 0,
      sellerShippingCost: 3000,
      customerShippingCost: 0,
      packagingCost: 500,
      materialCost: 200,
      advertisingCost: 1000,
      otherCosts: 0,
      sellingPriceVatIncluded: true,
      wholesaleVatType: 'included',
      targetMarginRate: 25,
    },
  },
  {
    id: 'coupang_rg',
    name: '쿠팡 로켓그로스',
    description: '로켓그로스 뷰티 2만원 (물류비 포함)',
    values: {
      sellingPrice: 20000,
      productCost: 6000,
      discountRate: 0,
      discountAmount: 0,
      platformFeeRate: 9.6,
      paymentFeeRate: 0,
      couponBurden: 0,
      sellerShippingCost: 0,
      customerShippingCost: 0,
      packagingCost: 0,
      materialCost: 0,
      advertisingCost: 500,
      otherCosts: 3000,
      sellingPriceVatIncluded: true,
      wholesaleVatType: 'included',
      targetMarginRate: 20,
    },
  },
  {
    id: 'beauty',
    name: '뷰티 셀러 예시',
    description: '자사몰에서 2만5천원 화장품 판매',
    values: {
      sellingPrice: 25000,
      productCost: 8000,
      discountRate: 0,
      discountAmount: 0,
      platformFeeRate: 0,
      paymentFeeRate: 3.3,
      couponBurden: 0,
      sellerShippingCost: 0,
      customerShippingCost: 3000,
      packagingCost: 800,
      materialCost: 300,
      advertisingCost: 1000,
      otherCosts: 0,
      sellingPriceVatIncluded: true,
      wholesaleVatType: 'included',
      targetMarginRate: 40,
    },
  },
  {
    id: 'clothing',
    name: '의류 셀러 예시',
    description: '에이블리에서 3만원 의류 판매',
    values: {
      sellingPrice: 30000,
      productCost: 10000,
      discountRate: 0,
      discountAmount: 0,
      platformFeeRate: 3.3,
      paymentFeeRate: 4.36,
      couponBurden: 0,
      sellerShippingCost: 3000,
      customerShippingCost: 0,
      packagingCost: 500,
      materialCost: 200,
      advertisingCost: 500,
      otherCosts: 0,
      sellingPriceVatIncluded: true,
      wholesaleVatType: 'included',
      targetMarginRate: 35,
    },
  },
];
