import type { PlatformPreset, SalesChannel } from '@/types';

/**
 * 플랫폼별 수수료 프리셋 (2025-2026 최신 기준)
 *
 * 참고: 수수료는 정책 변경에 따라 달라질 수 있습니다.
 * - 쿠팡: 마켓플레이스(자체배송) / 로켓그로스 / 로켓배송 구분
 * - 스마트스토어: 2025년 6월 개편 기준 (판매수수료 + 매출등급별 결제수수료)
 * - 오픈마켓: G마켓/옥션/11번가 카테고리별 차등
 */
export const PLATFORM_PRESETS: Record<SalesChannel, PlatformPreset> = {
  coupang: {
    id: 'coupang',
    name: '쿠팡',
    platformFeeRate: 10.8,
    paymentFeeRate: 0,
    subOptions: [
      // ── 마켓플레이스 (자체배송) ──
      {
        id: 'coupang_mp_fashion',
        name: '패션의류/잡화',
        tag: '마켓플레이스',
        description: '자체배송 · 의류, 신발, 가방, 잡화',
        platformFeeRate: 10.5,
        paymentFeeRate: 0,
      },
      {
        id: 'coupang_mp_beauty',
        name: '뷰티',
        tag: '마켓플레이스',
        description: '자체배송 · 화장품, 스킨케어, 헤어케어',
        platformFeeRate: 9.6,
        paymentFeeRate: 0,
      },
      {
        id: 'coupang_mp_food',
        name: '식품',
        tag: '마켓플레이스',
        description: '자체배송 · 식품, 건강식품 (쌀/잡곡 5.8%)',
        platformFeeRate: 8.9,
        paymentFeeRate: 0,
      },
      {
        id: 'coupang_mp_food_noodle',
        name: '면/라면/즉석',
        tag: '마켓플레이스',
        description: '자체배송 · 면, 라면, 즉석식품',
        platformFeeRate: 10.9,
        paymentFeeRate: 0,
      },
      {
        id: 'coupang_mp_living',
        name: '생활용품',
        tag: '마켓플레이스',
        description: '자체배송 · 생활용품, 주방, 욕실',
        platformFeeRate: 7.8,
        paymentFeeRate: 0,
      },
      {
        id: 'coupang_mp_electronics',
        name: '가전/디지털',
        tag: '마켓플레이스',
        description: '자체배송 · 전자제품, 컴퓨터, 모바일',
        platformFeeRate: 5.0,
        paymentFeeRate: 0,
      },
      {
        id: 'coupang_mp_jewelry',
        name: '쥬얼리',
        tag: '마켓플레이스',
        description: '자체배송 · 쥬얼리, 시계',
        platformFeeRate: 4.0,
        paymentFeeRate: 0,
      },
      {
        id: 'coupang_mp_book',
        name: '도서/음반/문구',
        tag: '마켓플레이스',
        description: '자체배송 · 도서, 음반, 문구',
        platformFeeRate: 10.8,
        paymentFeeRate: 0,
      },
      {
        id: 'coupang_mp_baby',
        name: '출산/유아동',
        tag: '마켓플레이스',
        description: '자체배송 · 유아용품, 아동복, 완구',
        platformFeeRate: 8.5,
        paymentFeeRate: 0,
      },
      // ── 로켓그로스 (위탁배송) ──
      {
        id: 'coupang_rg_fashion',
        name: '패션의류/잡화',
        tag: '로켓그로스',
        description: '위탁배송 · 의류, 신발, 가방 (판매수수료 + 물류비 별도)',
        platformFeeRate: 10.5,
        paymentFeeRate: 0,
        logisticsCostNote: '물류비: 소형 ~2,400원, 중형 ~4,300원, 대형 ~12,000원 (입출고+배송)',
        extraFees: [
          { label: '보관료', description: '45일 초과 시 일 25~100원/건' },
          { label: '반품 회수비', description: '소형 2,000원 / 중형 3,000원 / 대형 5,000원' },
        ],
      },
      {
        id: 'coupang_rg_beauty',
        name: '뷰티',
        tag: '로켓그로스',
        description: '위탁배송 · 화장품, 스킨케어 (판매수수료 + 물류비 별도)',
        platformFeeRate: 9.6,
        paymentFeeRate: 0,
        logisticsCostNote: '물류비: 초소형 ~1,950원, 소형 ~3,000원 (입출고+배송)',
        extraFees: [
          { label: '보관료', description: '45일 초과 시 일 25~50원/건' },
          { label: '반품 회수비', description: '소형 2,000원 / 중형 3,000원' },
        ],
      },
      {
        id: 'coupang_rg_food',
        name: '식품',
        tag: '로켓그로스',
        description: '위탁배송 · 식품, 건강식품 (판매수수료 + 물류비 별도)',
        platformFeeRate: 8.9,
        paymentFeeRate: 0,
        logisticsCostNote: '물류비: 소형 ~3,000원, 중형 ~4,300원 (입출고+배송)',
        extraFees: [
          { label: '보관료', description: '30일 초과 시 일 25~100원/건 (식품 무료기간 짧음)' },
          { label: '반품 회수비', description: '소형 2,000원 / 중형 3,000원' },
        ],
      },
      {
        id: 'coupang_rg_living',
        name: '생활용품',
        tag: '로켓그로스',
        description: '위탁배송 · 생활용품, 주방 (판매수수료 + 물류비 별도)',
        platformFeeRate: 7.8,
        paymentFeeRate: 0,
        logisticsCostNote: '물류비: 소형 ~3,000원, 중형 ~4,300원, 대형 ~12,000원 (입출고+배송)',
        extraFees: [
          { label: '보관료', description: '45일 초과 시 일 25~100원/건' },
          { label: '반품 회수비', description: '소형 2,000원 / 중형 3,000원 / 대형 5,000원' },
        ],
      },
      {
        id: 'coupang_rg_electronics',
        name: '가전/디지털',
        tag: '로켓그로스',
        description: '위탁배송 · 전자제품, 컴퓨터 (판매수수료 + 물류비 별도)',
        platformFeeRate: 5.0,
        paymentFeeRate: 0,
        logisticsCostNote: '물류비: 중형 ~4,300원, 대형 ~12,000원 (입출고+배송)',
        extraFees: [
          { label: '보관료', description: '45일 초과 시 일 50~100원/건' },
          { label: '반품 회수비', description: '중형 3,000원 / 대형 5,000원' },
        ],
      },
      {
        id: 'coupang_rg_baby',
        name: '출산/유아동',
        tag: '로켓그로스',
        description: '위탁배송 · 유아용품, 아동복 (판매수수료 + 물류비 별도)',
        platformFeeRate: 8.5,
        paymentFeeRate: 0,
        logisticsCostNote: '물류비: 소형 ~3,000원, 중형 ~4,300원 (입출고+배송)',
        extraFees: [
          { label: '보관료', description: '45일 초과 시 일 25~100원/건' },
          { label: '반품 회수비', description: '소형 2,000원 / 중형 3,000원' },
        ],
      },
    ],
  },

  smartstore: {
    id: 'smartstore',
    name: '스마트스토어',
    platformFeeRate: 2.73,
    paymentFeeRate: 3.63,
    subOptions: [
      // ── 유입 경로별 ──
      {
        id: 'smartstore_general',
        name: '일반 거래',
        tag: '유입경로',
        description: '네이버쇼핑 검색/추천 유입 (판매 2.73% + 결제 3.63%)',
        platformFeeRate: 2.73,
        paymentFeeRate: 3.63,
      },
      {
        id: 'smartstore_direct',
        name: '직접 유입 (마케팅링크)',
        tag: '유입경로',
        description: '판매자 마케팅 링크/SNS 유입 (판매 0.91% + 결제 3.63%)',
        platformFeeRate: 0.91,
        paymentFeeRate: 3.63,
      },
      {
        id: 'smartstore_brand',
        name: '브랜드스토어',
        tag: '유입경로',
        description: '브랜드스토어 입점 (판매 3.64% + 결제 3.63%)',
        platformFeeRate: 3.64,
        paymentFeeRate: 3.63,
      },
      {
        id: 'smartstore_brand_direct',
        name: '브랜드스토어 (마케팅링크)',
        tag: '유입경로',
        description: '브랜드스토어 + 마케팅링크 유입 (판매 1.82% + 결제 3.63%)',
        platformFeeRate: 1.82,
        paymentFeeRate: 3.63,
      },
      {
        id: 'smartstore_live',
        name: '쇼핑라이브',
        tag: '유입경로',
        description: '네이버 쇼핑라이브 (판매 0.91% + 결제 3.63%)',
        platformFeeRate: 0.91,
        paymentFeeRate: 3.63,
      },
      {
        id: 'smartstore_oneplus',
        name: '원쁠딜',
        tag: '유입경로',
        description: '원쁠딜 프로모션 (판매 2.73% + 결제 3.63%)',
        platformFeeRate: 2.73,
        paymentFeeRate: 3.63,
      },
      // ── 매출등급별 결제수수료 ──
      {
        id: 'smartstore_tier_3',
        name: '3억 이하',
        tag: '매출등급',
        description: '연매출 3억 이하 (판매 2.73% + 결제 1.98%)',
        platformFeeRate: 2.73,
        paymentFeeRate: 1.98,
      },
      {
        id: 'smartstore_tier_5',
        name: '3~5억',
        tag: '매출등급',
        description: '연매출 3~5억 (판매 2.73% + 결제 2.585%)',
        platformFeeRate: 2.73,
        paymentFeeRate: 2.585,
      },
      {
        id: 'smartstore_tier_10',
        name: '5~10억',
        tag: '매출등급',
        description: '연매출 5~10억 (판매 2.73% + 결제 2.75%)',
        platformFeeRate: 2.73,
        paymentFeeRate: 2.75,
      },
      {
        id: 'smartstore_tier_30',
        name: '10~30억',
        tag: '매출등급',
        description: '연매출 10~30억 (판매 2.73% + 결제 3.025%)',
        platformFeeRate: 2.73,
        paymentFeeRate: 3.025,
      },
      {
        id: 'smartstore_tier_over30',
        name: '30억 초과 / 신규',
        tag: '매출등급',
        description: '연매출 30억 초과 또는 신규 판매자 (판매 2.73% + 결제 3.63%)',
        platformFeeRate: 2.73,
        paymentFeeRate: 3.63,
      },
      // ── N배송관 / 솔루션 ──
      {
        id: 'smartstore_ndelivery',
        name: 'N배송관',
        tag: '특수채널',
        description: 'N배송관 입점 (판매수수료 0% + 결제 3.63%)',
        platformFeeRate: 0,
        paymentFeeRate: 3.63,
      },
    ],
  },

  open_market: {
    id: 'open_market',
    name: '오픈마켓',
    platformFeeRate: 12,
    paymentFeeRate: 0,
    subOptions: [
      // ── G마켓 ──
      {
        id: 'gmarket_fashion',
        name: '패션/뷰티',
        tag: 'G마켓',
        description: '의류, 화장품, 쥬얼리, 시계',
        platformFeeRate: 13,
        paymentFeeRate: 0,
        extraFees: [
          { label: '배송비 수수료', description: '유료배송 시 배송비의 3.3%' },
          { label: '서버이용료', description: '전월 판매대금 500만원 이상 시 월 55,000원' },
        ],
      },
      {
        id: 'gmarket_general',
        name: '일반 (생활/가전)',
        tag: 'G마켓',
        description: '생활용품, 가전 등',
        platformFeeRate: 12,
        paymentFeeRate: 0,
        extraFees: [
          { label: '배송비 수수료', description: '유료배송 시 배송비의 3.3%' },
          { label: '서버이용료', description: '전월 판매대금 500만원 이상 시 월 55,000원' },
        ],
      },
      {
        id: 'gmarket_digital',
        name: '디지털/컴퓨터',
        tag: 'G마켓',
        description: '컴퓨터, USB, 주변기기',
        platformFeeRate: 5,
        paymentFeeRate: 0,
        extraFees: [
          { label: '배송비 수수료', description: '유료배송 시 배송비의 3.3%' },
          { label: '서버이용료', description: '전월 판매대금 500만원 이상 시 월 55,000원' },
        ],
      },
      {
        id: 'gmarket_medical',
        name: '의료용품',
        tag: 'G마켓',
        description: '일반의료용품, 건강관리',
        platformFeeRate: 11,
        paymentFeeRate: 0,
        extraFees: [
          { label: '배송비 수수료', description: '유료배송 시 배송비의 3.3%' },
        ],
      },
      // ── 옥션 ──
      {
        id: 'auction_fashion',
        name: '패션/뷰티',
        tag: '옥션',
        description: '의류, 화장품, 쥬얼리, 시계',
        platformFeeRate: 13,
        paymentFeeRate: 0,
        extraFees: [
          { label: '배송비 수수료', description: '유료배송 시 배송비의 3.3%' },
          { label: '서버이용료', description: '전월 판매대금 500만원 이상 시 월 55,000원' },
        ],
      },
      {
        id: 'auction_general',
        name: '일반 (생활/가전)',
        tag: '옥션',
        description: '생활용품, 가전 등',
        platformFeeRate: 12,
        paymentFeeRate: 0,
        extraFees: [
          { label: '배송비 수수료', description: '유료배송 시 배송비의 3.3%' },
          { label: '서버이용료', description: '전월 판매대금 500만원 이상 시 월 55,000원' },
        ],
      },
      {
        id: 'auction_digital',
        name: '디지털/컴퓨터',
        tag: '옥션',
        description: '컴퓨터, USB, 주변기기',
        platformFeeRate: 5,
        paymentFeeRate: 0,
        extraFees: [
          { label: '배송비 수수료', description: '유료배송 시 배송비의 3.3%' },
        ],
      },
      // ── 11번가 ──
      {
        id: '11st_fashion',
        name: '패션/뷰티',
        tag: '11번가',
        description: '의류, 화장품, 쥬얼리',
        platformFeeRate: 13,
        paymentFeeRate: 0,
        extraFees: [
          { label: '배송비 수수료', description: '유료배송 시 배송비의 3.3%' },
          { label: '서버이용료', description: '전월 구매확정액 500만원 이상 시 월 77,000원' },
          { label: '제휴 수수료', description: '외부채널(네이버/다음 등) 유입 시 2%' },
        ],
      },
      {
        id: '11st_general',
        name: '일반 카테고리',
        tag: '11번가',
        description: '일반 카테고리 (생활, 가전 등)',
        platformFeeRate: 12,
        paymentFeeRate: 0,
        extraFees: [
          { label: '배송비 수수료', description: '유료배송 시 배송비의 3.3%' },
          { label: '서버이용료', description: '전월 구매확정액 500만원 이상 시 월 77,000원' },
          { label: '제휴 수수료', description: '외부채널(네이버/다음 등) 유입 시 2%' },
        ],
      },
      {
        id: '11st_digital',
        name: '디지털/컴퓨터',
        tag: '11번가',
        description: '컴퓨터, 전자제품',
        platformFeeRate: 7,
        paymentFeeRate: 0,
        extraFees: [
          { label: '배송비 수수료', description: '유료배송 시 배송비의 3.3%' },
          { label: '서버이용료', description: '전월 구매확정액 500만원 이상 시 월 77,000원' },
        ],
      },
      {
        id: '11st_new_seller',
        name: '신규셀러 프로모션',
        tag: '11번가',
        description: '신규 셀러 1년간 수수료 인하',
        platformFeeRate: 6,
        paymentFeeRate: 0,
        extraFees: [
          { label: '프로모션', description: '입점 후 1년간 최대 7%p 인하 적용' },
        ],
      },
    ],
  },

  ably: {
    id: 'ably',
    name: '에이블리',
    platformFeeRate: 3,
    paymentFeeRate: 3.96,
    subOptions: [
      {
        id: 'ably_sellers',
        name: '에이블리 셀러스',
        tag: '자체배송',
        description: '일반 셀러 (플랫폼 3% + 결제 3.96%, VAT별도)',
        platformFeeRate: 3.3,
        paymentFeeRate: 4.36,
      },
      {
        id: 'ably_partners',
        name: '에이블리 파트너스',
        tag: '위탁/풀필먼트',
        description: '위탁판매/풀필먼트 (수수료 포함)',
        platformFeeRate: 20,
        paymentFeeRate: 0,
        logisticsCostNote: '물류비 포함된 통합 수수료',
      },
    ],
  },

  zigzag: {
    id: 'zigzag',
    name: '지그재그',
    platformFeeRate: 8.5,
    paymentFeeRate: 0,
    subOptions: [
      {
        id: 'zigzag_soho',
        name: '소호 (사입)',
        tag: '의류',
        description: '사입 방식 의류 판매',
        platformFeeRate: 8.5,
        paymentFeeRate: 0,
      },
      {
        id: 'zigzag_brand',
        name: '브랜드',
        tag: '의류',
        description: '브랜드 입점 (자사몰 방식)',
        platformFeeRate: 27,
        paymentFeeRate: 0,
      },
      {
        id: 'zigzag_beauty',
        name: '뷰티/키즈',
        tag: '카테고리',
        description: '뷰티, 키즈 카테고리',
        platformFeeRate: 27,
        paymentFeeRate: 0,
      },
      {
        id: 'zigzag_life',
        name: '라이프',
        tag: '카테고리',
        description: '라이프 카테고리',
        platformFeeRate: 18,
        paymentFeeRate: 0,
      },
      {
        id: 'zigzag_food',
        name: '푸드',
        tag: '카테고리',
        description: '푸드 카테고리',
        platformFeeRate: 15,
        paymentFeeRate: 0,
      },
    ],
  },

  own_mall: {
    id: 'own_mall',
    name: '자사몰',
    platformFeeRate: 0,
    paymentFeeRate: 3.2,
    subOptions: [
      {
        id: 'own_mall_pg_general',
        name: 'PG사 (일반)',
        tag: '결제수단',
        description: '연매출 30억 이상 기준',
        platformFeeRate: 0,
        paymentFeeRate: 3.2,
      },
      {
        id: 'own_mall_pg_small',
        name: 'PG사 (영세)',
        tag: '결제수단',
        description: '연매출 3억 이하 (토스페이먼츠 기준)',
        platformFeeRate: 0,
        paymentFeeRate: 1.65,
      },
      {
        id: 'own_mall_naverpay',
        name: '네이버페이',
        tag: '결제수단',
        description: '네이버페이 결제 연동 시',
        platformFeeRate: 0,
        paymentFeeRate: 2.8,
      },
      {
        id: 'own_mall_kakaopay',
        name: '카카오페이',
        tag: '결제수단',
        description: '카카오페이 결제 연동 시',
        platformFeeRate: 0,
        paymentFeeRate: 3.0,
      },
      {
        id: 'own_mall_tosspay',
        name: '토스페이',
        tag: '결제수단',
        description: '토스페이 결제 연동 시',
        platformFeeRate: 0,
        paymentFeeRate: 3.5,
      },
    ],
  },

  custom: {
    id: 'custom',
    name: '직접입력',
    platformFeeRate: 0,
    paymentFeeRate: 0,
  },
};

export const PLATFORM_OPTIONS = Object.values(PLATFORM_PRESETS);
